# $PostgreSQL: /cvsroot/pgsql-server/contrib/dbmirror/Makefile,v 1.1 2002/06/23 21:58:07 momjian Exp $

subdir = contrib/dbmirror
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = pending
DOCS = README.dbmirror

include $(top_srcdir)/contrib/contrib-global.mk
