#-------------------------------------------------------------------------
#
# $PostgreSQL: pgsql/src/backend/utils/mb/conversion_procs/euc_jp_and_sjis/Makefile,v 1.4 2007/02/09 15:55:58 petere Exp $
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/euc_jis_2004_and_shit_jis_2004
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= euc_jis_2004_and_shift_jis_2004

include $(srcdir)/../proc.mk
