#! /bin/sh
# Utility to remove manufacturer's oui table
# $PostgreSQL: pgsql/src/backend/utils/misc/guc.c,v 1.314 2006/03/07 02:54:23 momjian Exp $


args=

while [ $# -gt 0 ]
do
    case "$1" in
    --help)
        echo "Usage: $0 dbname"
        exit
        ;;
    *)
        args="$args $1"
        ;;
    esac
    shift
done

psql $args <<EOF
drop function manuf(macaddr);
drop table macoui;
EOF

exit
