#
# Makefile for optimizer
#
# $PostgreSQL: pgsql/src/backend/optimizer/Makefile,v 1.13 2007/02/09 15:55:58 petere Exp $
#

subdir = src/backend/optimizer
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = geqo path plan prep util

include $(top_srcdir)/src/backend/common.mk
