#
# Makefile for the storage manager subsystem
#
# $PostgreSQL: pgsql/src/backend/storage/Makefile,v 1.13 2007/02/09 15:55:58 petere Exp $
#

subdir = src/backend/storage
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = buffer file freespace ipc large_object lmgr page smgr

include $(top_srcdir)/src/backend/common.mk
