#!/bin/sh

# $PostgreSQL: pgsql/src/backend/utils/misc/guc.c,v 1.314 2006/03/07 02:54:23 momjian Exp $

for FILE
do
	if [ ! -f "$FILE.orig" ]
	then	cp $FILE $FILE.orig
	else	echo "$FILE.orig exists" 1>&2
	fi
done
