#!/bin/sh

# $PostgreSQL: pgsql/src/backend/utils/misc/guc.c,v 1.314 2006/03/07 02:54:23 momjian Exp $

if [ "$#" -eq 0 ]
then	APATH="."
else	APATH="$1"
fi
find $APATH -name '*.orig' -print | sort | while read FILE
do
	NEW="`dirname $FILE`/`basename $FILE .orig`"
	echo "$NEW" 1>&2
	diff -c $FILE $NEW
done
