#!/bin/sh

# $PostgreSQL: pgsql/src/tools/FAQ2txt,v 1.2 2008/04/19 12:52:51 momjian Exp $:

# Converts doc/src/FAQ/FAQ.html to text file doc/FAQ

lynx -force_html -dont_wrap_pre -dump -hiddenlinks=ignore -nolist "$@"
