#!/bin/sh

# $PostgreSQL: pgsql/src/tools/TODO2html,v 1.1 2008/04/19 12:34:54 momjian Exp $:

# Converts FAQ.html and FAQ_DEV.html to text files

lynx -force_html -dont_wrap_pre -dump -hiddenlinks=ignore -nolist "$@"
