#!/bin/sh

# $PostgreSQL: pgsql/src/backend/utils/misc/guc.c,v 1.314 2006/03/07 02:54:23 momjian Exp $

trap "rm -f /tmp/$$" 0 1 2 3 15
rm -f ./TAGS
find `pwd`/ -type f -name '*.[chyl]' -print | \
  xargs etags --append -o TAGS

find . -type d -print | \
while read DIR; do
  [ "$DIR" != "." ] && ln -f -s `pwd`/TAGS $DIR
done
