#!/bin/sh

# $PostgreSQL: pgsql/src/tools/make_etags,v 1.5 2009/01/14 21:28:32 petere Exp $

rm -f ./TAGS

find `pwd`/ -type f -name '*.[chyl]' -print |
	xargs etags --append -o TAGS

find . \( -name CVS -prune \) -o \( -name .git -prune \) -o -type d -print |
while read DIR
do	[ "$DIR" != "." ] && ln -f -s `pwd`/TAGS "$DIR"
done
